export type TabType = 'all' | 'room' | 'event';

export interface Offer {
    id: number;
    type: TabType;
    image: string;
    title: { ko: string; en: string; ja: string; zh: string };
    subtitle: { ko: string; en: string; ja: string; zh: string };
    desc: { ko: string; en: string; ja: string; zh: string };
    period: { ko: string; en: string; ja: string; zh: string };
    details: { ko: string[]; en: string[]; ja: string[]; zh: string[] };
    showHomeCta?: boolean; // 홈 카드에 '이 혜택으로 예약하기' CTA 노출 여부
}

export const offers: Offer[] = [
    {
        id: 1,
        type: 'room',
        image: '/images/events/early-bird.jpg',
        showHomeCta: true,
        title: { ko: '연박 할인 특가', en: 'Long-Stay Discount', ja: '連泊割引特価', zh: '连住折扣特价' },
        subtitle: { ko: '최대 15% 할인', en: 'Up to 15% OFF', ja: '最大15%OFF', zh: '最高15%折扣' },
        desc: { ko: '2박 이상 10% 할인, 7박 이상 15% 할인 (타 이벤트와 중복 적용 불가)', en: '10% off for 2+ nights, 15% off for 7+ nights (Cannot combine with other offers)', ja: '2泊以上10%OFF、7泊以上15%OFF（他イベントとの併用不可）', zh: '2晚以上9折，7晚以上85折（不可与其他优惠同时使用）' },
        period: { ko: '상시 운영', en: 'Always Available', ja: '常時開催', zh: '常年有效' },
        details: {
            ko: [
                '2박 이상 예약 시 객실 요금의 10%가 할인됩니다.',
                '7박 이상 예약 시 객실 요금의 15%가 할인됩니다.',
                '할인율은 객실 유형에 관계없이 동일하게 적용됩니다.',
                '다른 프로모션(미군 특가, 기업체 혜택 등)과 중복 적용이 불가합니다.',
                '이벤트 페이지의 [이 혜택으로 예약하기] 버튼을 통해서만 적용됩니다.',
                '결제는 체크인 시 호텔 현장에서 진행됩니다.',
                '체크인 24시간 전까지 무료 취소 가능합니다.',
            ],
            en: [
                '10% discount on room rates for stays of 2 nights or more.',
                '15% discount on room rates for stays of 7 nights or more.',
                'Discount applies equally regardless of room type.',
                'Cannot be combined with other promotions (Military Special, Corporate Benefits, etc.).',
                'Only available through the [Book with this offer] button on the Events page.',
                'Payment is processed on-site at the hotel upon check-in.',
                'Free cancellation up to 24 hours before check-in.',
            ],
            ja: [
                '2泊以上のご予約で客室料金が10%割引になります。',
                '7泊以上のご予約で客室料金が15%割引になります。',
                '割引率は客室タイプに関係なく一律適用されます。',
                '他のプロモーション（米軍特価、法人特典など）との併用はできません。',
                'イベントページの「この特典で予約する」ボタンからのみ適用されます。',
                'お支払いはチェックイン時にホテルにて行います。',
                'チェックイン24時間前まで無料キャンセル可能です。',
            ],
            zh: [
                '预订2晚以上可享客房价格10%折扣。',
                '预订7晚以上可享客房价格15%折扣。',
                '折扣率不分房型统一适用。',
                '不可与其他促销（美军特价、企业优惠等）同时使用。',
                '仅通过活动页面的「以此优惠预订」按钮时适用。',
                '付款在入住时于酒店前台进行。',
                '入住前24小时可免费取消。',
            ],
        },
    },
    {
        id: 2,
        type: 'event',
        image: '/images/events/booking-benefits.png',
        title: { ko: '홈페이지 예약 특전', en: 'Online Booking Benefits', ja: 'ホームページ予約特典', zh: '官网预订专享' },
        subtitle: { ko: '모든 예약자 공용 혜택', en: 'Benefits for All Guests', ja: '全予約者共通特典', zh: '所有预订者共享优惠' },
        desc: { ko: '라운지 무료 이용 · 회의실 대관 할인 · 라운지 커피&홍차 무료', en: 'Free lounge access · Meeting room discount · Complimentary coffee & tea at lounge', ja: 'ラウンジ無料利用 · 会議室割引 · ラウンジでコーヒー＆紅茶無料', zh: '免费使用休息室 · 会议室折扣 · 休息室免费咖啡和红茶' },
        period: { ko: '상시 운영', en: 'Always Available', ja: '常時開催', zh: '常年有效' },
        details: {
            ko: [
                '본 홈페이지를 통해 직접 예약하신 모든 고객에게 적용되는 혜택입니다.',
                '투숙 기간 동안 라운지를 무료로 이용하실 수 있습니다.',
                '회의실 대관 시 할인이 적용됩니다 (자세한 요금은 프론트 문의).',
                '라운지에서 커피와 아마드티(홍차)를 자유롭게 무료로 즐기실 수 있습니다 (체크인~체크아웃).',
                '다른 프로모션(얼리버드, 비즈니스 패키지 등)과 중복 적용이 가능합니다.',
                'OTA(야놀자, 여기어때 등) 예약은 적용 대상이 아닙니다.',
            ],
            en: [
                'These benefits apply to all guests who book directly through our website.',
                'Complimentary lounge access throughout your stay.',
                'Discounted meeting room rental (contact the front desk for rates).',
                'Coffee and Ahmad Tea (black tea) are freely available at the lounge at no charge (from check-in to check-out).',
                'Can be combined with other promotions (Early Bird, Business Package, etc.).',
                'Bookings through OTAs (third-party platforms) are not eligible.',
            ],
            ja: [
                '本ホームページから直接ご予約いただいたすべてのお客様に適用される特典です。',
                'ご滞在中、ラウンジを無料でご利用いただけます。',
                '会議室レンタル時に割引が適用されます（料金の詳細はフロントへお問い合わせください）。',
                'ラウンジでコーヒーとアーマッドティー(紅茶)を自由に無料でお楽しみいただけます（チェックイン～チェックアウト）。',
                '他のプロモーション（アーリーバード、ビジネスパッケージなど）との併用が可能です。',
                'OTA（第三者プラットフォーム）経由のご予約は対象外です。',
            ],
            zh: [
                '此优惠适用于通过本官网直接预订的所有客人。',
                '住宿期间可免费使用休息室。',
                '会议室租用享受折扣（详细价格请咨询前台）。',
                '休息室免费提供咖啡和Ahmad红茶，可自由享用（从入住到退房）。',
                '可与其他促销活动（早鸟特价、商务套餐等）同时使用。',
                '通过OTA（第三方平台）预订不适用。',
            ],
        },
    },
    {
        id: 4,
        type: 'event',
        image: '/images/events/military-special.png',
        showHomeCta: true,
        title: { ko: 'US MILITARY 스페셜 특가', en: 'US Military Special Rate', ja: 'US MILITARY スペシャル特価', zh: 'US MILITARY 特价优惠' },
        subtitle: { ko: '주말 할증 없는 $64 고정 요금 및 특별 혜택', en: 'Flat $64 Rate Every Day & Exclusive Perks', ja: '週末割増なし $64 固定料金＆特別特典', zh: '无周末加价 $64固定价格及专属福利' },
        desc: { ko: '1박 $64 고정 · 디럭스 무료 업그레이드 · 1인 조식 포함 · 웰컴 기프트', en: 'Flat $64/night · Free Deluxe upgrade · Breakfast included · Welcome Gift', ja: '1泊$64固定 · デラックス無料UP · 朝食1名付 · ウェルカムギフト', zh: '每晚$64固定 · 免费升级豪华房 · 含1人早餐 · 欢迎礼物' },
        period: { ko: '상시 운영', en: 'Always Available', ja: '常時開催', zh: '常年有效' },
        details: {
            ko: [
                '1박 $64 고정 요금 (주중/주말 동일 — 주말 할증 없음)',
                '스탠다드 → 디럭스 룸 무료 업그레이드',
                '1인 무료 조식 포함',
                '무료 레이트 체크아웃',
                '체크인 시 스페셜 웰컴 기프트 증정',
                '체크인 시 유효한 미군 ID(CAC) 또는 Veteran 신분증 제시 필수',
                '직계 가족(배우자, 자녀) 적용 가능',
                '타 프로모션 중복 불가',
                '사전 예약 시 예약 유형을 "군인"으로 선택해 주세요',
            ],
            en: [
                'Flat $64/night (No weekend surcharges — same rate every day)',
                'Free upgrade from Standard to Deluxe Room',
                'Breakfast for 1 included',
                'Complimentary Late Check-out',
                'Special Welcome Gift at check-in',
                'Valid US Military ID (CAC) or Veteran ID required at check-in',
                'Applies to immediate family (spouse, children)',
                'Cannot be combined with other offers',
                'Must select "Military" as your booking type when reserving online',
            ],
            ja: [
                '1泊$64固定料金（平日/週末同一 — 週末割増なし）',
                'スタンダード → デラックスルーム無料アップグレード',
                '1名様朝食無料',
                'レイトチェックアウト無料',
                'チェックイン時にスペシャルウェルカムギフト進呈',
                'チェックイン時に有効な米軍ID（CAC）またはVeteran IDの提示が必要です',
                '直系家族（配偶者・お子様）に適用可能',
                '他のプロモーションとの併用不可',
                'オンライン予約時は予約タイプを「軍人」に選択してください',
            ],
            zh: [
                '每晚$64固定价格（工作日/周末相同 — 无周末加价）',
                '标准房 → 豪华房免费升级',
                '含1人免费早餐',
                '免费延迟退房',
                '入住时赠送特别欢迎礼物',
                '入住时须出示有效美军ID（CAC）或退伍军人证',
                '适用于直系亲属（配偶、子女）',
                '不可与其他优惠同时使用',
                '在线预订时请选择"军人"预订类型',
            ],
        },
    },
    {
        id: 5,
        type: 'event',
        image: '/images/events/corporate-benefits.png',
        title: { ko: '기업체 특별 혜택', en: 'Corporate Benefits', ja: '法人特別特典', zh: '企业专属优惠' },
        subtitle: { ko: '기업 고객 맞춤 할인', en: 'Tailored Corporate Rates', ja: '法人向けカスタム割引', zh: '企业定制优惠' },
        desc: { ko: '기업 고객 대상 할인 및 우대 서비스 · 문의를 통해 맞춤 견적 제공', en: 'Custom rates & premium services for corporate clients · Contact us for a quote', ja: '法人顧客向け割引＆優待 · お問い合わせで見積もり提供', zh: '企业客户折扣及优质服务 · 联系我们获取报价' },
        period: { ko: '상시 운영', en: 'Always Available', ja: '常時開催', zh: '常年有效' },
        details: {
            ko: [
                '체크인 시 명함을 제출해 주세요.',
                '정기 이용 기업체의 경우 별도 협약을 통해 추가 혜택을 제공해 드립니다.',
                '세금계산서 발행이 가능합니다.',
                '자세한 요금 및 조건은 전화 또는 메신저로 문의해 주세요.',
                '사전 예약 시 예약 유형을 "기업체"로 선택해 주세요.',
                '다른 프로모션과 중복 적용이 불가합니다.',
            ],
            en: [
                'Please present your business card at check-in.',
                'Recurring corporate clients may receive additional benefits through a separate agreement.',
                'Tax invoices can be issued upon request.',
                'Please contact us by phone or messenger for detailed rates and conditions.',
                'Please select "Corporate" as your reservation type when booking online.',
                'Cannot be combined with other promotions.',
            ],
            ja: [
                'チェックイン時に名刺をご提出ください。',
                '定期ご利用の法人様には別途契約による追加特典をご提供いたします。',
                '請求書の発行が可能です。',
                '詳しい料金・条件はお電話またはメッセンジャーでお問い合わせください。',
                'オンライン予約時は予約タイプを「法人」に選択してください。',
                '他のプロモーションとの併用はできません。',
            ],
            zh: [
                '入住时请出示名片。',
                '定期使用的企业客户可通过另行协议获得额外优惠。',
                '可开具税务发票。',
                '详细价格及条件请通过电话或即时通讯联系我们。',
                '在线预订时请选择"企业"作为预订类型。',
                '不可与其他促销活动同时使用。',
            ],
        },
    },
];
