export type TabType = 'all' | 'room' | 'event';

export interface Offer {
    id: number;
    type: TabType;
    image: string;
    title: { ko: string; en: string; ja: string; zh: string };
    subtitle: { ko: string; en: string; ja: string; zh: string };
    desc: { ko: string; en: string; ja: string; zh: string };
    period: { ko: string; en: string; ja: string; zh: string };
    details: { ko: string[]; en: string[]; ja: string[]; zh: string[] };
}

export const offers: Offer[] = [
    {
        id: 1,
        type: 'room',
        image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?q=80&w=800&auto=format&fit=crop',
        title: { ko: '얼리버드 특가', en: 'Early Bird Deal', ja: 'アーリーバード特価', zh: '早鸟特价' },
        subtitle: { ko: '15% 할인', en: '15% OFF', ja: '15%OFF', zh: '15%折扣' },
        desc: { ko: '14일 전 예약 시 15% 할인 · 취소 불가 상품', en: '15% off when booked 14 days ahead · Non-refundable', ja: '14日前予約で15%OFF · キャンセル不可', zh: '提前14天预订享15%折扣 · 不可取消' },
        period: { ko: '상시 운영', en: 'Always Available', ja: '常時開催', zh: '常年有效' },
        details: {
            ko: [
                '체크인 14일 전까지 예약 시 객실 요금의 15%가 할인됩니다.',
                '본 상품은 취소 불가 상품입니다 (체크인 3일 전부터 취소·변경 불가).',
                '할인율은 객실 유형에 관계없이 동일하게 적용됩니다.',
                '다른 프로모션 및 할인과 중복 적용이 불가합니다.',
                '성수기(공휴일, 연말연시) 기간에는 적용이 제한될 수 있습니다.',
                '결제는 예약 시 선결제로 진행됩니다.',
            ],
            en: [
                '15% discount on room rates when booked at least 14 days before check-in.',
                'This is a non-refundable rate (no cancellation or modification within 3 days of check-in).',
                'Discount applies equally regardless of room type.',
                'Cannot be combined with other promotions or discounts.',
                'Restrictions may apply during peak seasons (holidays, year-end).',
                'Full prepayment is required at the time of booking.',
            ],
            ja: [
                'チェックイン14日前までのご予約で客室料金が15%割引になります。',
                '本商品はキャンセル不可です（チェックイン3日前からキャンセル・変更不可）。',
                '割引率は客室タイプに関係なく一律適用されます。',
                '他のプロモーションや割引との併用はできません。',
                '繁忙期（祝日、年末年始）は適用が制限される場合があります。',
                'ご予約時に事前決済となります。',
            ],
            zh: [
                '入住前14天预订可享客房价格15%折扣。',
                '本产品不可取消（入住前3天起不可取消或修改）。',
                '折扣率不分房型统一适用。',
                '不可与其他促销或折扣同时使用。',
                '旺季（节假日、年末年初）期间可能有限制。',
                '预订时需全额预付。',
            ],
        },
    },
    {
        id: 2,
        type: 'room',
        image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?q=80&w=800&auto=format&fit=crop',
        title: { ko: '로맨틱 스테이', en: 'Romantic Stay', ja: 'ロマンティックステイ', zh: '浪漫之旅' },
        subtitle: { ko: '쿠폰 예약 시 와인 제공', en: 'Wine with Coupon Booking', ja: 'クーポン予約でワイン提供', zh: '优惠券预订赠红酒' },
        desc: { ko: '조식 포함 · 쿠폰 다운로드 후 예약 시 와인 1병 제공', en: 'Breakfast included · Book with coupon for a complimentary bottle of wine', ja: '朝食付き · クーポンダウンロード後の予約でワイン1本プレゼント', zh: '含早餐 · 下载优惠券预订赠红酒一瓶' },
        period: { ko: '상시 운영', en: 'Always Available', ja: '常時開催', zh: '常年有效' },
        details: {
            ko: [
                '2인 기준 패키지이며, 추가 인원 시 별도 요금이 발생합니다.',
                '2인 조식이 포함됩니다.',
                '본 페이지에서 쿠폰을 다운로드한 후 예약하시면 와인 1병이 제공됩니다.',
                '와인은 체크인 시 프론트에서 수령하실 수 있습니다.',
                '조식은 체크인 다음 날 이용 가능합니다.',
                '다른 프로모션과 중복 적용이 불가합니다.',
            ],
            en: [
                'Package is based on 2 guests; additional guests incur extra charges.',
                'Breakfast for 2 is included.',
                'Download the coupon from this page and book to receive a complimentary bottle of wine.',
                'Wine can be collected at the front desk upon check-in.',
                'Breakfast is available the morning after check-in.',
                'Cannot be combined with other promotions.',
            ],
            ja: [
                '2名様基準のパッケージです。追加人数には別途料金がかかります。',
                '2名様分の朝食が含まれます。',
                '本ページからクーポンをダウンロードしてご予約いただくと、ワイン1本をプレゼントいたします。',
                'ワインはチェックイン時にフロントでお受け取りいただけます。',
                '朝食はチェックイン翌日にご利用いただけます。',
                '他のプロモーションとの併用はできません。',
            ],
            zh: [
                '套餐以2人为基准，额外人员需另行收费。',
                '包含2人早餐。',
                '从本页面下载优惠券后预订，即赠红酒一瓶。',
                '入住时可在前台领取红酒。',
                '早餐于入住次日提供。',
                '不可与其他促销活动同时使用。',
            ],
        },
    },
    {
        id: 3,
        type: 'room',
        image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800&auto=format&fit=crop',
        title: { ko: '비즈니스 패키지', en: 'Business Package', ja: 'ビジネスパッケージ', zh: '商务套餐' },
        subtitle: { ko: '출장객 특별 혜택', en: 'Business Traveler Benefits', ja: 'ビジネス旅行者特典', zh: '商旅特别优惠' },
        desc: { ko: '조식 & 비즈니스 라운지 이용 포함', en: 'Breakfast & Business Lounge access included', ja: '朝食＆ビジネスラウンジ利用付き', zh: '含早餐及商务休息室使用' },
        period: { ko: '상시 운영', en: 'Always Available', ja: '常時開催', zh: '常年有效' },
        details: {
            ko: [
                '1인 조식이 포함됩니다.',
                '비즈니스 라운지를 이용하실 수 있습니다 (운영시간: 07:00 - 22:00).',
                '무료 고속 Wi-Fi 및 비즈니스 센터 이용이 포함됩니다.',
                '레이트 체크아웃(14:00)이 가능합니다 (객실 상황에 따라).',
                '다른 프로모션과 중복 적용이 불가합니다.',
            ],
            en: [
                'Breakfast for 1 guest is included.',
                'Access to the Business Lounge (operating hours: 7AM - 10PM).',
                'Complimentary high-speed Wi-Fi and business center access included.',
                'Late checkout (2PM) available subject to room availability.',
                'Cannot be combined with other promotions.',
            ],
            ja: [
                '1名様分の朝食が含まれます。',
                'ビジネスラウンジをご利用いただけます（営業時間：07:00〜22:00）。',
                '無料高速Wi-Fiおよびビジネスセンターのご利用が含まれます。',
                'レイトチェックアウト（14:00）が可能です（客室状況による）。',
                '他のプロモーションとの併用はできません。',
            ],
            zh: [
                '包含1人早餐。',
                '可使用商务休息室（营业时间：07:00 - 22:00）。',
                '包含免费高速Wi-Fi及商务中心使用。',
                '可延迟退房至14:00（视房间情况而定）。',
                '不可与其他促销活动同时使用。',
            ],
        },
    },
    {
        id: 4,
        type: 'event',
        image: 'https://images.unsplash.com/photo-1521791055366-0d553872125f?q=80&w=800&auto=format&fit=crop',
        title: { ko: '밀리터리 스페셜', en: 'Military Special', ja: 'ミリタリースペシャル', zh: '军人特惠' },
        subtitle: { ko: 'US Military 전용 혜택', en: 'Exclusive for US Military', ja: '米軍専用特典', zh: '美军专属优惠' },
        desc: { ko: '미군 ID카드 제시 시 특별 할인 & 선물 제공 · 자세한 내용은 문의', en: 'Special discount & gift with US Military ID · Contact us for details', ja: '米軍ID提示で特別割引＆ギフト · 詳細はお問い合わせ', zh: '出示美军ID享特别折扣及礼物 · 详情请咨询' },
        period: { ko: '상시 운영', en: 'Always Available', ja: '常時開催', zh: '常年有効' },
        details: {
            ko: [
                '체크인 시 유효한 미군 ID카드(CAC 또는 군인 신분증)를 제시해 주세요.',
                '본인 및 동반 가족(배우자, 자녀)에게 적용됩니다.',
                '할인율 및 혜택 내용은 객실 유형과 투숙 조건에 따라 달라지며, 전화 또는 메신저로 문의해 주시면 상세히 안내드립니다.',
                '체크인 시 스페셜 기프트를 제공해 드립니다.',
                '퇴역 군인(Veteran) ID도 적용 가능합니다.',
                '사전 예약 시 예약 유형을 "군인"으로 선택해 주세요.',
                '다른 할인 및 프로모션과 중복 적용이 불가합니다.',
            ],
            en: [
                'Please present a valid US Military ID (CAC or Military ID) at check-in.',
                'Applies to the cardholder and accompanying family members (spouse, children).',
                'Discount rates and benefits vary by room type and stay conditions. Please contact us by phone or messenger for detailed information.',
                'A special gift will be provided upon check-in.',
                'Veteran IDs are also accepted.',
                'Please select "Military" as your reservation type when booking online.',
                'Cannot be combined with other discounts or promotions.',
            ],
            ja: [
                'チェックイン時に有効な米軍IDカード（CACまたは軍人身分証）をご提示ください。',
                'ご本人および同伴のご家族（配偶者・お子様）に適用されます。',
                '割引率や特典内容は客室タイプや宿泊条件により異なります。お電話またはメッセンジャーでお問い合わせいただければ詳しくご案内いたします。',
                'チェックイン時にスペシャルギフトをご用意いたします。',
                '退役軍人IDも適用可能です。',
                'オンライン予約時は予約タイプを「軍人」に選択してください。',
                '他の割引やプロモーションとの併用はできません。',
            ],
            zh: [
                '入住时请出示有效的美军ID卡（CAC或军人身份证）。',
                '适用于持卡人及随行家属（配偶、子女）。',
                '折扣率和优惠内容因房型和住宿条件而异，请通过电话或即时通讯联系我们获取详细信息。',
                '入住时将提供特别礼物。',
                '退伍军人ID也可使用。',
                '在线预订时请选择"军人"作为预订类型。',
                '不可与其他折扣或促销活动同时使用。',
            ],
        },
    },
    {
        id: 5,
        type: 'event',
        image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=800&auto=format&fit=crop',
        title: { ko: '기업체 특별 혜택', en: 'Corporate Benefits', ja: '法人特別特典', zh: '企业专属优惠' },
        subtitle: { ko: '기업 고객 맞춤 할인', en: 'Tailored Corporate Rates', ja: '法人向けカスタム割引', zh: '企业定制优惠' },
        desc: { ko: '기업 고객 대상 할인 및 우대 서비스 · 문의를 통해 맞춤 견적 제공', en: 'Custom rates & premium services for corporate clients · Contact us for a quote', ja: '法人顧客向け割引＆優待 · お問い合わせで見積もり提供', zh: '企业客户折扣及优质服务 · 联系我们获取报价' },
        period: { ko: '상시 운영', en: 'Always Available', ja: '常時開催', zh: '常年有效' },
        details: {
            ko: [
                '체크인 시 사업자등록증 또는 재직증명서를 제시해 주세요.',
                '할인율은 객실 유형, 투숙 기간, 이용 빈도에 따라 협의 가능합니다.',
                '정기 이용 기업체의 경우 별도 협약을 통해 추가 혜택을 제공해 드립니다.',
                '세금계산서 발행이 가능합니다.',
                '자세한 요금 및 조건은 전화 또는 메신저로 문의해 주세요.',
                '사전 예약 시 예약 유형을 "기업체"로 선택해 주세요.',
                '다른 프로모션과 중복 적용이 불가합니다.',
            ],
            en: [
                'Please present a business registration certificate or employment verification at check-in.',
                'Discount rates are negotiable based on room type, duration of stay, and frequency of use.',
                'Recurring corporate clients may receive additional benefits through a separate agreement.',
                'Tax invoices can be issued upon request.',
                'Please contact us by phone or messenger for detailed rates and conditions.',
                'Please select "Corporate" as your reservation type when booking online.',
                'Cannot be combined with other promotions.',
            ],
            ja: [
                'チェックイン時に事業者登録証または在職証明書をご提示ください。',
                '割引率は客室タイプ、宿泊期間、ご利用頻度に応じて協議可能です。',
                '定期ご利用の法人様には別途契約による追加特典をご提供いたします。',
                '請求書の発行が可能です。',
                '詳しい料金・条件はお電話またはメッセンジャーでお問い合わせください。',
                'オンライン予約時は予約タイプを「法人」に選択してください。',
                '他のプロモーションとの併用はできません。',
            ],
            zh: [
                '入住时请出示营业执照或在职证明。',
                '折扣率可根据房型、住宿时间和使用频率协商。',
                '定期使用的企业客户可通过另行协议获得额外优惠。',
                '可开具税务发票。',
                '详细价格及条件请通过电话或即时通讯联系我们。',
                '在线预订时请选择"企业"作为预订类型。',
                '不可与其他促销活动同时使用。',
            ],
        },
    },
];
